# Generated by Django 5.2.10 on 2026-01-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='active',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='delete_status',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent_category', 'active', 'delete_status'], name='categories_parent__189c2d_idx'),
        ),
    ]
