# Generated by Django 5.2.10 on 2026-01-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (10, 'Confirmed'), (20, 'Processing'), (30, 'Shipped'), (40, 'Delivered'), (50, 'Cancelled')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.IntegerField(db_index=True),
        ),
    ]
