# Generated by Django 5.2.10 on 2026-01-11 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatushistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='orders.order'),
        ),
    ]
