# Generated by Django 5.2.10 on 2026-01-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_active_alter_category_delete_status_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='delete_status',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'active', 'delete_status'], name='products_categor_197c5d_idx'),
        ),
    ]
